language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11
services: mysql
before_install:
  - mysql -u root -e "CREATE DATABASE zerobot;"
  - mysql -u root zerobot < zerobot.sql
  - chmod +x ./gradlew
script:
  - ./gradlew build